### ISSUE TITLE
Sequencer does not retain order for concurrent inserts

### ISSUE THREAD

**Issue by frankmcsherry** [TimelyDataflow/timely-dataflow#223]
The `Sequencer` does not respect the order elements are pushed, in the case that the worker collects a batch of elements at one time. Instead, they are sorted by whatever `Ord` implementation they have. Instead, the implementation should probably maintain another `usize` for local sequence number, so that the order pushed by each worker is reflected in the results.

**Comment by comnik** [comment]
This should be solved with #224, right?

**Comment by frankmcsherry** [comment]
Fixed by #224!
