### ISSUE TITLE
Examples in mdbook

### ISSUE THREAD

**Issue by danalex97** [TimelyDataflow/timely-dataflow#240]
I was wondering if some of the examples in the [mdbook](http://timelydataflow.github.io/timely-dataflow/chapter_2/chapter_2_4.html) correspond to the current release version(0.8.0). For example, shouldn't this [code](http://timelydataflow.github.io/timely-dataflow/chapter_2/chapter_2_4.html#capabilities) be something similar to [this one](https://docs.rs/timely/0.8.0/timely/dataflow/operators/generic/operator/fn.source.html)? How can I find out what version does the mdbook use?

Thank you. :smile:

**Comment by frankmcsherry** [comment]
This is a good point. The mdbook examples are tested against the *current* master code (they get tested on each check in). This means they are a bit ahead of 0.8, at the moment. We are about ready to drop a 0.9 release, and then they would correspond.

I agree that this is awkward, and I'm not sure the best way to get examples against 0.8. The documentation at [docs.rs/timely](https://docs.rs/timely/0.8.0/timely/) should be tested against 0.8, so the corresponding `source` example would be this: https://docs.rs/timely/0.8.0/timely/dataflow/operators/generic/operator/fn.source.html

**Comment by danalex97** [comment]
Thank you! My bad, I saw this mentioned both in the readme and book introductory example.
