### ISSUE TITLE
Misleading use of HashMap in the book

### ISSUE THREAD

**Issue by vorner** [TimelyDataflow/timely-dataflow#254]
Hello

I'm reading through the book and I've noticed that multiple times a HashMap is used to stash yet unavailable data in a custom operator, for example here: https://timelydataflow.github.io/timely-dataflow/chapter_2/chapter_2_5.html#maintaining-word-counts. The claim made in the book is, this'll make sure we process the data in order.

I don't think this is the case, if I get everything correctly:
* HashMap doesn't store the timestamps in order, so the `iter_mut` may go through them in arbitrary order.
* One call of the closure could advance by multiple timestamps at once (eg. there was a laggard batch of data that unblocked whole bunch of older batches that were waiting just for it).
* All these can be released at once, but in the order of iteration, producing some „broken“ partial responses on the way.

The whole example is correct, because it doesn't let a timestamp + 1 until the old timestamp is flushed from the system, but I think this might lead to surprises when someone gets inspired by the example of the operator and let's the whole dataflow work as fast as it can, without pausing for flush.

Would it be possible to either point the problem out, or use `BTreeMap` that *does* preserve order of keys (and point it out)?

**Comment by frankmcsherry** [comment]
Your reasoning is correct! It's definitely bad to misrepresent what will happen. I'll look into a fix over the weekend.

**Comment by frankmcsherry** [comment]
This specific example should be fixed up with the PR. There are probably others. Generally, the mdbook code is tested, but the text and examples drift in and out of relevance to the surrounding text. happy to fix things as they are noticed.
