### ISSUE TITLE
Detecting closed inputs and producing work afterwards

### ISSUE THREAD

**Issue by abreis** [TimelyDataflow/timely-dataflow#259]
I'd like to build an operator that:
* gathers data from an input stream;
* produces a single summary value of that stream once it closes.

Can (will?) an operator be scheduled for work after its inputs close?  
And can it know the difference between an input that has no data and one that has closed?

If I could be pointed in the right direction I'd be very grateful.

**Comment by frankmcsherry** [comment]
I would start with the timely dataflow book, reading up to the subsection on [Frontiered Operators](https://timelydataflow.github.io/timely-dataflow/chapter_2/chapter_2_4.html#frontiered-operators). These are operators that can inspect the *future* times at which they may receive data, which among other things will tell them when their inputs are complete. Specifically, once an input frontier is equal to `&[]`, the empty slice, then it is complete (there are no timestamps for which future messages might arrive).

**Comment by frankmcsherry** [comment]
And yup operators will be scheduled when closed, at least once. Operators are scheduled when any of 

1. input data arrive,
2. frontier information changes (future timestamps that might arrive),
3. someone explicitly asks to schedule the operator.

This means that an operator whose stream has closed will be scheduled, at least once more. After that scheduling, we may not schedule the operator and may actually close the operator (if the operator holds no capabilities it cannot produce any more output, and we'll shut it down unless it requests to stay open).

**Comment by abreis** [comment]
Ah, I was missing that intuition about frontiers. Thank you very much!
