### ISSUE TITLE
release 0.9.0 build failure

### ISSUE THREAD

**Issue by bmmcq** [TimelyDataflow/timely-dataflow#269]
As title: 
![image](https://user-images.githubusercontent.com/32241292/57276830-42a58700-70d5-11e9-8cb4-23976d00a5c5.png)

**Comment by frankmcsherry** [comment]
This seems to be the same as this issue: https://github.com/rust-lang/rust/issues/56398 which has been fixed in more recent Rust releases. Could you update your Rust version and double check?
