### ISSUE TITLE
Documentation: a little detail

### ISSUE THREAD

**Issue by rasa200** [TimelyDataflow/timely-dataflow#272]
Hi there!!! (Thanks for the great initiative!!)

I was reading the documentation, the mdbook in fact, and in the "Iteration" [subsection](https://timelydataflow.github.io/timely-dataflow/chapter_4/chapter_4_2.html), inside "Advance Timely Dataflow", in the first code there is, you can note that there is a line missing in the code:
`.branch_when(|t| t < &100).1`

This is in the documentation of the [feedback](https://docs.rs/timely/0.9.0/timely/dataflow/operators/feedback/trait.Feedback.html) function (that is why I found it). Maybe you want to put it also in the mdbook :)

That's all!! 
Cheers!!

**Comment by frankmcsherry** [comment]
Absolutely correct! For historical reasons, it used to be built in to the feedback operator, but is no more. I'll put together a fix!

**Comment by frankmcsherry** [comment]
Thanks very much!
