### ISSUE TITLE
Help: How to setup connection

### ISSUE THREAD

**Issue by rasa200** [TimelyDataflow/timely-dataflow#273]
I am sorry if this is a very basic question (no experience with distributed computing yet), but I really wanted to try timely-dataflow "at home", but I could not make the connection work.

I am working in windows 10 machines (only two), and setup a ssh connection, with no password required (ssh keys), ie: from the command line I can access the other machine by just typing `ssh username@computername`. I thought that would be enough to make them "work as a cluster", but it didn't, 

do you have any suggestion to make the connection work "at home" with two windows machines?

Thanks beforhand!!

**Comment by frankmcsherry** [comment]
Hi,

Have you followed [the instructions on running with multiple processes](https://github.com/TimelyDataflow/timely-dataflow#execution) in which you put together a hostfile with addresses and ports? It's a bit hard to diagnose from your description (timely doesn't use SSH; it connects directly, which may require you to inform Windows' firewall / Defender).

**Comment by rasa200** [comment]
Thanks for the quick answer!!

I think that my problem is trying to do the connect over wifi, not using ethernet (or can I do it with wifi only?)

So, just to be clearer, this is what I do:

- Two computers, connected to the same internet.
- Both windows firewall deactivated.
- From computer1, I have this rust project that uses timely.
- From computer1, I initialize two cmds:
  + In cmd1, I ran `cargo run -- --w2 -h -hostplan.txt -n2 -p0`
  + In cmd2, I ran `cargo run -- --w2 -h -hostplan.txt -n2 -p1`

where hostplan.txt is in the directory of the rust project and hostplan.txt is simply:

computer1name:1
computer2name:1


Note: no command is run from computer2, is this wrong?


I will keep trying some things, post anything if I solve it.

**Comment by frankmcsherry** [comment]
You want to run commands on each machine where you want a process to run. In this case, it sounds like you probably do want to run one `cargo run` on each machine: the `-p0` one on `computer1` and the `-p1` one on `computer2`. You probably also want to use a port other than `1`, as .. it's probably already taken? I'd pick a larger number!

**Comment by rasa200** [comment]
Perfect!! Just as you said :) 

Just to recap the steps so that it works (in Windows at least)

0) Connect the computers to the same network

1) Choose one computer as the "main" computer, where the rust project is located.

2) From the other computers go to Network and enter to the main computer by filling the credentials (username and password of the main computer)

3) Open a command line in each computer and go to the same folder: in the main computer go there as usual, in the others, you need to use `pushd` instead of `cd` to go to folders in the main computer

4) Follow the step in timely-dataflow, running one `cargo run` per machine.


The funny thing is that it work for me in one direction (computer1 is the "main" one), but not in the other (computer2 the "main" one), for some permissions I couldn't setup well in windows: I have complete control from the other machine in the main one, I can delete files and everything, but when running cargo run it says I can't delete some file... And it happens only one way!  
If I find a clean way to fix it, I will post it here, in case it is useful for someone else.

Thanks for the help!!

**Comment by rasa200** [comment]
Hi there!! 

Assume you have two computer cp1 and cp2, both with windows. It seems that, unless you set some file (any file/folder works) to have access from cp2, cp2 can't see any file through the "Network" folder. 
I fixed this by giving access to "Everyone" to the rust project and worked perfectly.

So, I would add the following warning:
"In Windows, remember to give access to the project to the rest of the cluster in the "Give access to" option of the context menu. This allows the cluster to access (and view) all necessary files"
 

Thanks a lot!!
