### ISSUE TITLE
no method named `exchange` found for type ...  in the current scope

### ISSUE THREAD

**Issue by ahwatts** [TimelyDataflow/timely-dataflow#288]
So I was attempting to update my app to timely / differential 0.10, and am running in to this error:

```
error[E0599]: no method named `exchange` found for type `timely::dataflow::stream::Stream<G, ((std::string::String, operators::song_plays::PlayEvent<D>), <G as timely::dataflow::scopes::ScopeParent>::Timestamp, R)>` in the current scope
   --> govpec/src/operators/song_plays.rs:537:14
    |
537 |             .exchange(|((session_id, _), _, _)| {
    |              ^^^^^^^^
    |
    = note: the method `exchange` exists but the following trait bounds were not satisfied:
            `timely::dataflow::stream::Stream<G, ((std::string::String, operators::song_plays::PlayEvent<D>), <G as timely::dataflow::scopes::ScopeParent>::Timestamp, R)> : timely::dataflow::operators::exchange::Exchange<_, _>`
```

Aside from the Rust compiler not being too helpful about what part of the `Exchange` trait I'm not implementing, I suspect the issue is that while `PlayEvent<D>` implements `Abomonation` through `abomonation_derive`, but differential, timely, and timely_communication appear to depend on different versions of that crate:

```
awatts@ironic-mullet govpec [master *=] $ cargo tree -i -p abomonation_derive:0.3.0
abomonation_derive v0.3.0
├── differential-dataflow v0.10.0
│   └── governess-pectin v0.5.0 (/home/awatts/Work/event-processing/rust/govpec)
└── timely v0.10.0
    ├── differential-dataflow v0.10.0 (*)
    └── governess-pectin v0.5.0 (/home/awatts/Work/event-processing/rust/govpec) (*)
awatts@ironic-mullet govpec [master *=] $ cargo tree -i -p abomonation_derive:0.4.0
abomonation_derive v0.4.0
├── governess-pectin v0.5.0 (/home/awatts/Work/event-processing/rust/govpec)
└── timely_communication v0.10.0
    ├── governess-pectin v0.5.0 (/home/awatts/Work/event-processing/rust/govpec) (*)
    └── timely v0.10.0
        ├── differential-dataflow v0.10.0
        │   └── governess-pectin v0.5.0 (/home/awatts/Work/event-processing/rust/govpec) (*)
        └── governess-pectin v0.5.0 (/home/awatts/Work/event-processing/rust/govpec) (*)
```

They do all agree on `abomonation` itself, though:

```
awatts@ironic-mullet govpec [master *=] $ cargo tree -i -p abomonation
abomonation v0.7.3
├── differential-dataflow v0.10.0
│   └── governess-pectin v0.5.0 (/home/awatts/Work/event-processing/rust/govpec)
├── governess-pectin v0.5.0 (/home/awatts/Work/event-processing/rust/govpec) (*)
├── timely v0.10.0
│   ├── differential-dataflow v0.10.0 (*)
│   └── governess-pectin v0.5.0 (/home/awatts/Work/event-processing/rust/govpec) (*)
└── timely_communication v0.10.0
    ├── governess-pectin v0.5.0 (/home/awatts/Work/event-processing/rust/govpec) (*)
    └── timely v0.10.0 (*)
```

(`governess-pectin` is the nonsense name for my app)

I suspect this is the issue because the `Exchange` trait wants the data to be `ExchangeData`, which winds up being `'static + Clone + Send + Sync + Any + Abomonation`, which is pretty general, except for the `Abomonation` trait. But I could be wrong about that, too.

**Comment by ahwatts** [comment]
Actually, I don't think that's my issue. Sorry.

**Comment by ahwatts** [comment]
In case someone comes across this later: My problem was that the diff type, `R`, didn't impl `ExchangeData` any more.

**Comment by frankmcsherry** [comment]
Aha! I'd love to get better diagnostics from Rust's type inference somehow. If you come up with any good lived experience about debugging this (or what could have helped along the way) I'm all ears.

**Comment by ahwatts** [comment]
The way I deduced it was essentially to start breaking down the tuple that was being `Exchange`d until I narrowed down the type that was causing the problem.

I originally had `R: differential_dataflow::Diff + Copy`, and changing it to `R: Diff + Copy + ExchangeData` fixed it.

I probably should just get rid of the generic on the diff type and assume it's always an `i64`.
