### ISSUE TITLE
Better documentation for `timely::execute`

### ISSUE THREAD

**Issue by ryzhyk** [TimelyDataflow/timely-dataflow#293]
The documentation for `timely::execute()` does not specify when the function returns.  The description says "Starts a timely dataflow execution...", and so I expected the function to return immediately after starting the worker threads.  Experimentally, however, it seems to only return when the dataflow is terminating.  Is this the intended behavior?  If so, it should probably be documented.

**Comment by frankmcsherry** [comment]
It should return almost immediately. It spawns several threads with the dataflow assembly instructions and then returns an instance of `JoinGuards` which wraps handles to each of the worker threads and their possible results. If you *drop* that result, the drop code will block awaiting the completion. More about that type here: https://github.com/TimelyDataflow/timely-dataflow/blob/master/communication/src/initialize.rs#L277-L306

**Comment by ryzhyk** [comment]
Aha, that was it, I was dropping the `WorkerGuards`. I still think it is worth documenting this behavior. Will try to write it up and submitting a PR.
