### ISSUE TITLE
What's the right way to ingest real world datasets?

### ISSUE THREAD

**Issue by top1select** [TimelyDataflow/timely-dataflow#307]
Hello,

I've been searching through your repositories and documentations, and it seems in order to use data files for the input graphs, you need to convert them into GraphMap format first.

So is this the recommended way to ingest real world graph datasets? Or there are other straight forward methods?

Thanks!

**Comment by frankmcsherry** [comment]
You can take any of the examples that use the GraphMap format and use them as a guide, where you replace reading the data from that format with a reader from whichever formats you prefer. You get to write them yourself!

**Comment by top1select** [comment]
Thanks for the quick response.
