### ISSUE TITLE
`state_machine` may act on inputs before the frontier has advanced past them (or maybe not)

### ISSUE THREAD

**Issue by utaal** [TimelyDataflow/timely-dataflow#316]
I believe that in this code

https://github.com/TimelyDataflow/timely-dataflow/blob/4b4752ec7447253ac61c9804c9cf6406dabfc281/timely/src/dataflow/operators/aggregation/state_machine.rs#L93-L99

the condition on line 94 may need to be `if notificator.frontier(0).less_equal(time.time()) {`, that is: we need to wait to act on all times that are in advance of the frontier. I believe that includes times that are equal to an element in the frontier, similarly to https://github.com/TimelyDataflow/timely-dataflow/blob/4b4752ec7447253ac61c9804c9cf6406dabfc281/timely/src/dataflow/operators/generic/notificator.rs#L324

**Comment by frankmcsherry** [comment]
Hrm. Can you say more? Is there a specific error you have seen? There was a bug here before, but we lifted the notification code above the input processing (to ensure that pended times were processed before eager input processing). If the condition is strengthened as you suggest I think we should just remove it, as it should be impossible to receive a time for which the frontier is not less_equal to it.

**Comment by utaal** [comment]
I think I see what I was missing here (which is also why this deviates from the common pattern of delaying processing for things that are in advance of the frontier). The comment says:

```
`state_machine` will buffer inputs if earlier inputs may still arrive. it will directly apply
updates for the current time reflected in the notificator, though.
```

So (in total order) if the frontier is `[t1]` we would be applying messages at `t1` to the state while we still believe we may be seeing additional inputs at `t1` (but no inputs at times strictly less than `t1`). When `t1` retires from the frontier, we move forward to the next candidate time. If this is correct, I think this is indeed _not_ a bug.

**Comment by frankmcsherry** [comment]
I think that reading is correct. The title of the issue seems correct tbh, but that per the (ill-explained) intent of ` `state_machine` it isn't out of spec. The larger intent, fwiw, is that `state_machine` is used in conjunction with the `aggregate` operator to reduce the number of records at each distinct time with each distinct key down to one, at which point `state_machine` probably (possibly?) makes a lot more sense.
