### ISSUE TITLE
How to: Pass resource into Map closure

### ISSUE THREAD

**Issue by gregberns** [TimelyDataflow/timely-dataflow#318]
Just getting started with Timely and running into an issue trying to pass a 'resource' in to use in a computation. I'm still struggling with closures in rust so maybe thats the problem, but I can't seem to figure out how to pass the resource into a map or flat_map or any function that uses a closure. Is there a way to do this? I'm sure I'm just doing something wrong but can't figure it out.

```
cannot infer an appropriate lifetime due to conflicting requirements

note: ...so that the types are compatible:
      expected &&mut std::string::String
         found &&mut std::string::String
note: but, the lifetime must be valid for the static lifetime...rustc(E0495)
```

Example Reproduce:

```
use timely::dataflow::operators::ToStream;

timely::execute_from_args(::std::env::args(), |worker| {
    let resource = "hello".to_string();

    worker.dataflow_core::<usize, _, _, _>("dataflow X", None, resource, |resources, scope| {
        (0..10)
            .to_stream(scope)

//ERROR HERE  V                                               V
            .map(|x| format!("{:?} {:?}", resources, x))

            .inspect(|x| println!("seen: {:?}", x));
    });
});

```

**Comment by frankmcsherry** [comment]
You'll almost certainly want to use the `move` keyword on the map closure:
```rust
.map(move |x| format!("{:?} {:?}", resources, x))
```
This tells Rust that you should move the ownership of closed-over bindings into the closure.

**Comment by frankmcsherry** [comment]
Also, from experience, you'll often be ok using the same keyword to capture the resource in the dataflow closure, without needing to use `dataflow_core`:
```rust
    let resource = "hello".to_string();
    worker.dataflow<usize, _, _>(move |scope| {
        (0..10)
            .to_stream(scope)
            .map(move |x| format!("{:?} {:?}", resource, x))
            .inspect(|x| println!("seen: {:?}", x));
    });
```
The cases where `dataflow_core` have come up (for me) have been settings where you need to very carefully control dropping of resources (e.g. unmapping of shared libraries, whose code is needed in other parts of the dataflow drop code).

**Comment by gregberns** [comment]
Ah yes, there needed to be a move on both the `dataflow` closure and the `map` closure, that makes sense. Only issue is if you want to use the resource twice - in two different map statements, but I can deal with that.

Theres another issue though once the two moves are added. If the `InputHandle` and `ProbeHandle` are used, like in many of the examples, there's a conflict with the `move` because its consuming the handles so they can't be used in the `for` loop below.

Is there a way around that?

```
timely::execute_from_args(::std::env::args(), |worker| {
    let index = worker.index();
    let mut input = InputHandle::new();
    let mut probe = ProbeHandle::new();

    let resource = "hello".to_string();
    worker.dataflow::<usize, _, _>(move |scope| {
        scope
            .input_from(&mut input)
            .map(move |x| format!("{:?} {:?}", resource, x))
            .inspect(|x| println!("seen: {:?}", x))
            .probe_with(&mut probe);
    });

    for round in 0..10 {
        if index == 0 {
//ERROR V  -- "value borrowed here after move"
            input.send(round);
        }
        input.advance_to(round + 1);
//ERROR    V  -- "value borrowed here after move"
        while probe.less_than(input.time()) {
            worker.step();
        }
    }
});
```

**Comment by frankmcsherry** [comment]
Idiomatic Rust would probably have you create references and move those, so e.g.
```rust
    let mut input = InputHandle::new();
    let mut probe = ProbeHandle::new();

    let input_ref = &mut input;
    let probe_ref = &mut probe;
    let resource = "hello".to_string();
    worker.dataflow::<usize, _, _>(move |scope| {
        scope
            .input_from(input_ref)
            .map(move |x| format!("{:?} {:?}", resource, x))
            .inspect(|x| println!("seen: {:?}", x))
            .probe_with(probe_ref);
    });
```
though, probably other ways. You can create the string inside the dataflow closure, for example, and not need to move it. Generally you can get around `move` by creating references if you'd prefer to borrow some arguments (but, lifetimes are a thing and `dataflow` works but the `map` closure doesn't, as it needs to have `static` lifetime).

**Comment by gregberns** [comment]
Wonderful, I haven't used that pattern before, thanks for the help!!
