### ISSUE TITLE
Should provide python api?

### ISSUE THREAD

**Issue by zhanglistar** [TimelyDataflow/timely-dataflow#324]
You know, python is simple and easy to use.

**Comment by frankmcsherry** [comment]
Thanks for the thought! It seems not especially easy to do, and isn't on the roadmap for this specific project. It seems very reasonable for someone else to think through what that would require, though!

Closing as out of scope for the project, but not a bad idea at all!

**Comment by davidselassie** [comment]
@zhanglistar We are working on a stream processing library for Python built on top of Timely over at https://github.com/bytewax/bytewax. It's still very much in progress, but our eventual plan is to provide a similar way to build dataflows in Python, let you use existing Python libraries in your computation, and provide higher-level features like fault tolerance / recovery, pre-built connectors for inputs and outputs, and deployment tooling. We'd love for you (or whoever else finds this) to give it a spin and any feedback!
