### ISSUE TITLE
Change DEFAULT_PROGRESS_MODE to TIMELY_PROGRESS_MODE

### ISSUE THREAD

**Issue by rjnn** [TimelyDataflow/timely-dataflow#347]
`DEFAULT_PROGRESS_MODE` caused some confusion when it showed up in a log message in Materialize (materializeinc/materialize#5055) as unset. This was primarily due to the fact that nowhere in the name does it say which runtime it refers to. A convention on ENV variables could help here (e.g. jemalloc env variables begin with `MALLOC_`, and `DIFFERENTIAL_EAGER_MERGE` being the other env variable already begins with differential), if that isn't terribly disruptive to existing users. Happy to gin up a PR if this proposal is acceptable, want to check first.

**Comment by frankmcsherry** [comment]
Addressed in https://github.com/TimelyDataflow/timely-dataflow/pull/350
