### ISSUE TITLE
Too casually nested regions / scopes hang

### ISSUE THREAD

**Issue by frankmcsherry** [TimelyDataflow/timely-dataflow#377]
The following program hangs after printing twice, even on a single worker
```rust
extern crate timely;

use timely::dataflow::{InputHandle, ProbeHandle};
use timely::dataflow::operators::{Input, Exchange, Inspect, Probe};

use crate::timely::dataflow::Scope;
use crate::timely::dataflow::operators::{Enter, Leave};

fn main() {
    // initializes and runs a timely dataflow.
    timely::execute_from_args(std::env::args(), |worker| {

        let index = worker.index();
        let mut input = InputHandle::new();
        let mut probe = ProbeHandle::new();

        // create a new input, exchange data, and inspect its output
        worker.dataflow(|scope| {
            let data = scope.input_from(&mut input);

            scope.region(|inner| {

                let data = data.enter(inner);
                inner.region(|inner2| data.enter(inner2).leave()).leave()
            })
                .inspect(move |x| println!("worker {}:\thello {}", index, x))
                .probe_with(&mut probe);
        });

        // introduce data and watch!
        for round in 0..10 {
            if index == 0 {
                input.send(round);
            }
            input.advance_to(round + 1);
            while probe.less_than(input.time()) {
                worker.step_or_park(None);
            }
        }
    }).unwrap();
}
```
It does not hang if a trivial operator is inserted between the inner `enter` and `leave` operators.

**Comment by Kixiron** [comment]
I think this could be the issue at play in [differential-datalog/#931](https://github.com/vmware/differential-datalog/pull/931)

**Comment by frankmcsherry** [comment]
Can you say more about the issue there? I could believe that adding more regions could gum things up for whatever reason is at play here. But, if you have something specific that you were seeing (exactly the same behavior, or .. ?).

**Comment by Kixiron** [comment]
Pretty much the exact same behavior, I'm not really entirely sure what caused it though, my best guesses are me eliminating some [scary transmutes](https://github.com/vmware/differential-datalog/pull/931/files?diff=split&w=1#diff-809c223f7a00662c0d3e9cee045374d39566837fd3e27c8920cfbcdcd8dcadfcL1447-L1450) to do with scoping or (as a stretch) something to do with the new [optimizations](https://github.com/vmware/differential-datalog/pull/931/files?diff=split&w=1#diff-e0e93968b5fbc23fa5c53ac23f2ccea543e4b2eccf4d71cafa6c35446db23cf7R54) I added that allowed not doing trivial operations between enter/leave cycles?

**Comment by frankmcsherry** [comment]
I think I've found the problem. A scope with no operators .. has nothing that will activate it. A message passing in to and out of it traverses no operators, and causes no activation to happen. This leaves the progress information of the message successfully transiting the scope in limbo, never communicated upwards.

Shouldn't be too hard to fix.
