### ISSUE TITLE
Build timely cluster

### ISSUE THREAD

**Issue by QiZhang1997** [TimelyDataflow/timely-dataflow#483]
How to build a timely-dataflow cluster, is there any documentation for guidance? Thanks a lot！

**Comment by frankmcsherry** [comment]
The `readme.md` file has a section on multi-process execution: https://github.com/TimelyDataflow/timely-dataflow#execution

**Comment by QiZhang1997** [comment]
OK! Thanks! I have started the cluster following the tutorial. I noticed you posted the example of pagerank in the documentation, I would like to ask if there are other kinds of graph algorithm examples implemented by timely-dataflow, such as weak connected components(WCC) and label propagation(LP).
